In [1]:
import numpy as np

# 对一维数组切片

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[5:8] #对数组进行切片 获取5-8位

array([5, 6, 7])

In [6]:
a2 = arr[2:8:2] #获取2-8位，隔2位获取一个数字
a2

array([2, 4, 6])

In [8]:
a2[0] = 100
a2

array([100,   4,   6])

In [9]:
arr

array([  0,   1, 100,   3,   4,   5,   6,   7,   8,   9])

## 对切片后的数组进行修改也会影响切片前的数组

In [11]:
a3 = arr[5:8].copy() #把arr中的5-8位复制到了a3中，此时再修改a3不会影响arr
a3[0] = 200
a3

array([200,   6,   7])

In [12]:
arr

array([  0,   1, 100,   3,   4,   5,   6,   7,   8,   9])

# 对高位数组进行切片

In [13]:
a4 = np.arange(24).reshape(2,3,4)
a4

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [15]:
a4[0] #取出第一个 3x4数组

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
a4[0][0] #第一个3x4数组的第一行

array([0, 1, 2, 3])

In [17]:
a4[0][0][0] #第一个3x4数组的第一行的第一个

0

In [18]:
a4[1,2,3] #同 a4[1][2][3]

23

In [23]:
a4[:,0,1:4] #取出每一个 3x4 数组的第一行的第1-4位

array([[ 1,  2,  3],
       [13, 14, 15]])

在切片时，可以这么简化：
- **获取所有** $:$
- **获取前k位** $:k$
- **获取第k位到最后一位** $k:$

# 布尔索引

In [25]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [26]:
a > 10 #此时会产生一个bool类型的数组，其中第 i 位表示 a[i] > 10 的运算结果

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [27]:
a[a>10] #取出bool数组中全部的true的数 及原数组 a中所有的大于10的数

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [28]:
a[(a>5)&(a<14)]

array([ 6,  7,  8,  9, 10, 11, 12, 13])

In [31]:
def check(a):
    return (a>2)&(a<10)
a[check(a)] #也可以使用函数

array([3, 4, 5, 6, 7, 8, 9])

In [32]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [34]:
(a>10)&(a%2 == 1)

array([[[False, False, False, False],
        [False, False, False, False],
        [False, False, False,  True]],

       [[False,  True, False,  True],
        [False,  True, False,  True],
        [False,  True, False,  True]]])

In [36]:
a[(a>10)&(a%2 == 1)] #对高维数组使用bool索引，得到的是一维数组

array([11, 13, 15, 17, 19, 21, 23])