In [1]:
import numpy as np

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.sqrt(a) #求 a的每一个元素的平方根，比for循环改快

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [4]:
np.sin(a) #求 sin函数

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [5]:
np.cos(a) #求 cos函数

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [6]:
a**2 #每一个数取幂

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [7]:
b = np.arange(10,0,-1) #同range()函数
b

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [8]:
np.maximum(a,b) #要保证 a,b两个数组符合广播的要求
#此函数会返回一个新的数组其中数组的第 k 位为 a中第 k位和 b中第 k位之间较大的数

array([10,  9,  8,  7,  6,  5,  6,  7,  8,  9])

In [9]:
a - b

array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8])

# **统计方法**

In [10]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.mean(a) #求均值

4.5

In [12]:
a.mean()

4.5

In [13]:
np.sum(a) #求和

45

In [14]:
a.sum()

45

In [15]:
a1 = a.reshape(2,5)
a1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
a1.mean(axis = 1)#求一行的均值

array([2., 7.])

In [17]:
a1.mean(0) #简写，等同于a1.mean(axis = 0)

array([2.5, 3.5, 4.5, 5.5, 6.5])

In [18]:
np.max(a1)

9

In [19]:
np.min(a1,axis = 1)

array([0, 5])

In [20]:
np.std(a1,axis = 1) #求每一行的标准差

array([1.41421356, 1.41421356])

In [21]:
np.median(a1,axis = 1) #求每一行的中位数

array([2., 7.])

# 数学相关函数
- sum 总和
- mean 算数平均值
- median 中位数
- quantile(k) 分位数，其中 $k$ 是 $0-1$ 之间的小数
- max 最大值
- min 最小值
- ptp 极值
- var 方差
- std 标准差

In [22]:
b = np.random.randint(1,10,6)
b

array([1, 2, 7, 6, 8, 5])

In [23]:
c = b > 5
c.all() #判断 bool数组中所有元素是不是都为 True

False

In [24]:
c.any() #判断 bool数组中含不含有 True

True

In [25]:
b.dump("b-data") #保存数组到二进制文件中
c = np.load("b-data",allow_pickle = True) #从文件中读取数组
c

array([1, 2, 7, 6, 8, 5])

In [26]:
b.tofile("b-value.txt",sep=",") #将数组内元素写入文件中

In [27]:
c = b.reshape(2,3)
c

array([[1, 2, 7],
       [6, 8, 5]])

In [28]:
c.flatten() #多维数组展开成一维数组

array([1, 2, 7, 6, 8, 5])

In [29]:
b

array([1, 2, 7, 6, 8, 5])

In [30]:
b.sort() #对数组排序
b

array([1, 2, 5, 6, 7, 8])