In [1]:
import numpy as np

In [2]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [3]:
a + 10 #此时 a中的所有数字都会 +10   --广播

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [4]:
a + a #形状相同的数组运算时，会将对应位置的数运算

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [5]:
a * a

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [7]:
a1 = np.arange(5)
a1

array([0, 1, 2, 3, 4])

In [8]:
a + a1 #由于 a1的大小恰好是 a的一行所以此时会把 a的每一行与 a1相加

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

In [9]:
a1 = np.arange(4)
a + a1 #此时会报错，因为a a1既不相似也不相互包含

ValueError: operands could not be broadcast together with shapes (2,5) (4,) 

In [10]:
a1 = np.arange(2).reshape(2,1)
a1

array([[0],
       [1]])

In [11]:
a + a1 #每一列对应相加

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

# 数组的转置（和学线性代数一样）

In [12]:
a.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])