In [1]:
import numpy as np

# 数组合并
## 常用的方法

In [2]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [3]:
np.concatenate((a,b)) #连接a,b(默认沿着0轴)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [4]:
np.concatenate((a,b),axis = 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

默认情况下，我们认为：行的方向是0轴（从上到下），列（从左到右）的方向是1轴
当然，对于一维的数组合并时，我们只会把一个数组放到另一个后面（也就是沿着1轴）

## 另一种合并的方法

In [5]:
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])

In [6]:
np.stack((a1,a2)) #增加维度，把a1,a2当作两个元素

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# 添加元素

In [7]:
a1

array([1, 2, 3, 4])

In [20]:
np.append(a1,5)
# 注意！append会返回一个新数组，而不是在原数组上改变

array([1, 2, 3, 4, 5])

In [9]:
b

array([[5, 6],
       [7, 8]])

In [16]:
np.append(b,[[9,10]],axis = 0)
# 对于高维数组，如果没有提供轴，程序会默认把数组展开

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [19]:
np.append(b,[[0],[0]],axis = 1)

array([[5, 6, 0],
       [7, 8, 0]])

# 数组元素去重

In [21]:
a = np.array([1,2,1,1,1,4,5,6,7,3,2,2])
np.unique(a) #这个函数也是返回一个新数组，不会改变a

array([1, 2, 3, 4, 5, 6, 7])