In [1]:
import numpy as np

# 创建数组

In [2]:
a = np.array([1,2,3]) #用可迭代对象创建

In [3]:
a

array([1, 2, 3])

In [4]:
a = np.array((4,5,6)) #使用元组创建

In [5]:
a

array([4, 5, 6])

In [6]:
a = np.array([[1,2,3],[4,5,6]]) #多维数组创建array

In [7]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
a.ndim #显示维度（数组的秩）

2

In [9]:
a.shape #显示数组的形状 行,列

(2, 3)

In [10]:
a.dtype #显示数据类型

dtype('int32')

In [11]:
a = np.zeros(10) #创建一个全为 0的数组括号内输入形状
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
a = np.ones((3,3)) #创建一个全 1的数组
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
a.ndim

2

In [14]:
a.shape

(3, 3)

In [15]:
a.dtype

dtype('float64')

In [16]:
a = np.empty((2,3,4)) # 创建一个"空"的数组(里面是随机数)
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

## 对于高维数组的解释：
```
a = np.zeros((2,3,4))
a
```
运行结果：
```
array([[[0., 0., 0., 0.,],
        [0., 0., 0., 0.,],
        [0., 0., 0., 0.,]],

       [[0., 0., 0., 0.,],
        [0., 0., 0., 0.,],
        [0., 0., 0., 0.,]]])
```
可以理解为： **2**个**3**行**4**列的数组

In [17]:
b = np.arange(10) #arange(k)可以按顺序生成一个从0 - k-1的一维数组
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
b.reshape(2,5) #改变数组的形状 必须保证大小一致！

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
b = np.linspace(0,10,100) #生成一个等差数列，从0-10，一共100个数
b

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [27]:
b = np.logspace(1,10,num = 10,base = 2) #生成一个等比数列
#等比数列的起始值是 2^1 终止值是 2^10 num是生成的数的个数，base是底数
b

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [28]:
b = np.fromstring("1,2,3,4,5",sep=',')
b

array([1., 2., 3., 4., 5.])

In [30]:
b = np.full((3,4),10) #生成一个大小为3x4 内容全为 10的数组
b

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [32]:
b = np.eye(4) #生成一个单位矩阵
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# 数组的属性
- size 数组内元素的个数
- shape 数组的形状
- dtype 数组元素的数据类型
- ndim 数组的维度
- itemsize 获取数组单个元素占用内存空间的字节数
- nbytes 获取数组所有元素占用内存空间的字节数

## 自定义数据类型

In [20]:
c = np.array([1,2,3],dtype = np.float32)
c

array([1., 2., 3.], dtype=float32)

In [21]:
c = np.zeros(10,dtype = np.int32)
c

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# 数据类型大全
## 整形(int)
- int16 16位
- int32 32位
- int64 64位
- uint8 无符号整型
- uint16 32 64
## 浮点型(float)
- float16
- float32
- float64
## 布尔型(bool) true/false

In [22]:
d = np.array([True,False])
d

array([ True, False])

In [23]:
np.array(['a','ab'])

array(['a', 'ab'], dtype='<U2')

# 数据类型转换

In [24]:
d.astype(np.int16)

array([1, 0], dtype=int16)

In [25]:
d.astype(np.float64)

array([1., 0.])